# Generated by Django 5.0.6 on 2024-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gate_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_pass_id', models.CharField(max_length=70)),
                ('gp_student_id', models.IntegerField(max_length=70)),
                ('gp_pass_date', models.DateField(max_length=70)),
                ('gp_pass_time', models.TimeField(max_length=70)),
                ('gp_pass_destination', models.CharField(max_length=70)),
                ('gp_pass_purpose', models.CharField(max_length=70)),
                ('gp_pass_issued_by', models.IntegerField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='student_address_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stad_address_details_address_id', models.CharField(max_length=300)),
                ('stad_address_details_student_id', models.CharField(max_length=300)),
                ('stad_address_details_address_type', models.CharField(max_length=300)),
                ('stad_address_details_city', models.CharField(max_length=300)),
                ('stad_address_details_state', models.CharField(max_length=300)),
                ('stad_address_details_country', models.CharField(max_length=300)),
                ('stad_address_details', models.IntegerField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.IntegerField(max_length=70)),
                ('sd_student_code', models.IntegerField(max_length=70)),
                ('sd_first_name', models.CharField(max_length=70)),
                ('sd_last_name', models.CharField(max_length=70)),
                ('sd_date_of_birth', models.DateField(max_length=60)),
                ('sd_gender', models.CharField(max_length=70)),
                ('sd_email', models.EmailField(max_length=70)),
                ('sd_city', models.CharField(max_length=70)),
                ('sd_semester', models.IntegerField(max_length=70)),
                ('sd_branch_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='studentregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_first_name', models.CharField(max_length=70)),
                ('sr_last_name', models.CharField(max_length=70)),
                ('sr_phone_no', models.IntegerField(max_length=70)),
                ('sr_country', models.CharField(max_length=70)),
                ('sr_city', models.CharField(max_length=70)),
                ('sr_state', models.CharField(max_length=70)),
                ('sr_fee_type_id', models.CharField(max_length=70)),
                ('sr_program_applied', models.CharField(max_length=70)),
                ('sr_course_applied', models.CharField(max_length=70)),
                ('sr_application_status', models.CharField(max_length=70)),
                ('sr_application_date', models.CharField(max_length=70)),
                ('sr_admission_date', models.DateField(max_length=70)),
            ],
        ),
    ]
